[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edgarito"
version = "0.1.1"
description = "Retrieve and normalize company financial data from SEC EDGAR"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11,<4",
    "pydantic>=2.10,<3",
    "python-dotenv>=1,<2",
]
authors = [
    { name = "Jean-François Kener", email = "betterask.jf@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.optional-dependencies]
dev = ["pytest>=8"]

[project.scripts]
edgarito = "edgarito.cli.__main__:main"

[tool.setuptools.packages.find]
include = ["edgarito", "edgarito.*"]
exclude = ["venv_windows", "venv", "cache"]
