from importlib import import_module

from edgarito.services.valuation.assumptions import (
    CostOfEquityResolver,
    ResolvedCostOfEquityAssumptions,
    ResolvedDcfAssumptions,
    ValuationAssumptionResolver,
)
from edgarito.services.valuation.comparable_implied import (
    ComparableImpliedValuationService,
    ForwardPeerMultiplesService,
    HistoricalMultiplesService,
    MultipleResolver,
)
from edgarito.services.valuation.decision import (
    BoundedRootFinder,
    DecisionScenarioPolicy,
    DecisionValuationService,
    IntrinsicDecisionContext,
    IntrinsicDecisionEngine,
    ReverseDcfService,
    ScenarioValuationService,
    SensitivityAnalysisService,
)
from edgarito.services.valuation.decision_models import (
    DecisionScenario,
    DecisionValuationResult,
    IntrinsicScenarioCase,
    PriceComparison,
    RelativeScenarioCase,
    RelativeScenarioTimeBasis,
    ReverseDcfSolution,
    ReverseDcfStatus,
    ReverseDcfVariable,
    ScenarioAssumption,
    SensitivityCell,
    SensitivityTable,
    ValuationAssessment,
    ValuationAssessmentBand,
)
from edgarito.services.valuation.depreciable_asset_life import (
    DepreciableAssetLifeResolution,
    DepreciableAssetLifeResolver,
)
from edgarito.services.valuation.discounting import (
    DiscountRateService,
    PresentValueService,
    TerminalValueService,
)
from edgarito.services.valuation.fcff_dcf import (
    FcffDcfCapitalBridgeResolver,
    FcffDcfService,
)
from edgarito.services.valuation.fx import EcbMarketDataCurrencyConverter
from edgarito.services.valuation.models import (
    BusinessArchetype,
    CashFlow,
    CashFlowTiming,
    CompanyLifecycle,
    CompanyTradingMultiples,
    ComparableImpliedValuation,
    ComparableImpliedValuationCase,
    ComparableMultiplesReport,
    CostOfEquityMethod,
    CostOfEquityResult,
    Cyclicality,
    DataReadiness,
    DiscountedCashFlow,
    EconomicTrait,
    FcffDcfCapitalBridge,
    FcffDcfParameters,
    FcffDcfResult,
    FcffDcfShareDilutionSensitivity,
    FinancialInstitutionKind,
    ForecastProfile,
    HistoricalMultipleObservation,
    HistoricalMultipleSummary,
    LtmFundamentals,
    ModelRole,
    ModelSuitability,
    MultipleConfidence,
    MultipleStatus,
    PeerCandidateAssessment,
    PeerDiscoveryResult,
    PeerEvidenceGroup,
    PeerMultipleSummary,
    PeerSelectionParameters,
    PeerUniverse,
    PresentValueResult,
    RelativeValuationBasis,
    ResolvedMultiple,
    ShareCountBasis,
    ShareRepurchaseParameters,
    ShareRepurchasePeriod,
    ShareRepurchaseResult,
    TerminalMetric,
    TerminalValueMethod,
    TerminalValueResult,
    TradingMultiple,
    ValuationInput,
    ValuationModel,
    ValuationProfile,
    ValuationProfileOverrides,
    ValuationSelection,
    WaccResult,
)
from edgarito.services.valuation.multiples import (
    ComparableMultiplesService,
    LtmMultiplesService,
)
from edgarito.services.valuation.peer_discovery import (
    MarketAwarePeerDiscoveryProvider,
    MassiveRelatedCompaniesPeerDiscoveryProvider,
    OpenAIPeerDiscoveryProvider,
    OpenAIPeerDiscoveryResponse,
    PeerCandidateDiscoveryProvider,
    YahooScreenerPeerDiscoveryProvider,
)
from edgarito.services.valuation.peers import PeerUniverseSelector
from edgarito.services.valuation.profile import ValuationProfileBuilder
from edgarito.services.valuation.selector import ValuationModelSelector
from edgarito.services.valuation.specialized import (
    BiotechInputExtractor,
    ReitInputExtractor,
    ResourceInputExtractor,
    SotpInputExtractor,
    SpecializedValuationExtractor,
)
from edgarito.services.valuation.terminal_roic import (
    TerminalRoicResolution,
    TerminalRoicResolver,
)

__all__ = [
    "BoundedRootFinder",
    "BusinessArchetype",
    "BiotechInputExtractor",
    "CashFlow",
    "CashFlowTiming",
    "CompanyTradingMultiples",
    "ComparableImpliedValuation",
    "ComparableImpliedValuationCase",
    "ComparableImpliedValuationService",
    "ComparableMultiplesReport",
    "ComparableMultiplesService",
    "CostOfEquityResolver",
    "CostOfEquityMethod",
    "CostOfEquityResult",
    "DividendDiscountService",
    "CompanyLifecycle",
    "Cyclicality",
    "DataReadiness",
    "DiscountedCashFlow",
    "DiscountRateService",
    "DecisionScenario",
    "DecisionScenarioPolicy",
    "DecisionValuationResult",
    "DecisionValuationService",
    "DepreciableAssetLifeResolution",
    "DepreciableAssetLifeResolver",
    "EconomicTrait",
    "EcbMarketDataCurrencyConverter",
    "ForecastProfile",
    "FinancialInstitutionKind",
    "HistoricalMultipleObservation",
    "HistoricalMultipleSummary",
    "LtmFundamentals",
    "IntrinsicDecisionContext",
    "IntrinsicDecisionEngine",
    "IntrinsicScenarioCase",
    "FcffDcfCapitalBridge",
    "FcffDcfCapitalBridgeResolver",
    "FcffDcfParameters",
    "FcffDcfResult",
    "FcffDcfShareDilutionSensitivity",
    "FcffDcfService",
    "FcfeDcfService",
    "ForwardPeerMultiplesService",
    "ModelRole",
    "ModelSuitability",
    "MultipleStatus",
    "MultipleConfidence",
    "MultipleResolver",
    "HistoricalMultiplesService",
    "LtmMultiplesService",
    "MarketAwarePeerDiscoveryProvider",
    "MassiveRelatedCompaniesPeerDiscoveryProvider",
    "OpenAIPeerDiscoveryProvider",
    "OpenAIPeerDiscoveryResponse",
    "PeerCandidateAssessment",
    "PeerCandidateDiscoveryProvider",
    "PeerDiscoveryResult",
    "PeerEvidenceGroup",
    "PeerMultipleSummary",
    "PeerSelectionParameters",
    "PeerUniverse",
    "PriceComparison",
    "PeerUniverseSelector",
    "YahooScreenerPeerDiscoveryProvider",
    "PresentValueResult",
    "PresentValueService",
    "PipelineRnpvAdapter",
    "PropertyNavAdapter",
    "ProviderNeutralForwardMultiplesService",
    "ProviderNeutralRelativeValuationService",
    "RelativeValuationBasis",
    "ResolvedMultiple",
    "RelativeScenarioCase",
    "RelativeScenarioTimeBasis",
    "ReverseDcfService",
    "ReverseDcfSolution",
    "ReverseDcfStatus",
    "ReverseDcfVariable",
    "ScenarioAssumption",
    "ScenarioValuationService",
    "SensitivityAnalysisService",
    "SensitivityCell",
    "SensitivityTable",
    "ShareRepurchaseParameters",
    "ShareRepurchasePeriod",
    "ShareRepurchaseResult",
    "ShareCountBasis",
    "ResolvedDcfAssumptions",
    "ResolvedCostOfEquityAssumptions",
    "ResidualIncomeService",
    "ReitAffoAdapter",
    "ReitInputExtractor",
    "ResourceInputExtractor",
    "ResourceNavAdapter",
    "SotpInputExtractor",
    "SotpValuationService",
    "SpecializedValuationExtractor",
    "TerminalMetric",
    "TerminalRoicResolution",
    "TerminalRoicResolver",
    "TerminalValueMethod",
    "TerminalValueResult",
    "TerminalValueService",
    "ValuationInput",
    "ValuationAssumptionResolver",
    "ValuationAssessment",
    "ValuationAssessmentBand",
    "ValuationExecutor",
    "ValuationInputCatalog",
    "ValuationModel",
    "ValuationModelSelector",
    "ValuationProfile",
    "ValuationProfileBuilder",
    "ValuationProfileOverrides",
    "ValuationSelection",
    "WaccResult",
    "TradingMultiple",
    "wrap_fcff_result",
]


_LAZY_EXPORTS = {
    "DividendDiscountService": (
        "edgarito.services.valuation.intrinsic",
        "DividendDiscountService",
    ),
    "FcfeDcfService": ("edgarito.services.valuation.intrinsic", "FcfeDcfService"),
    "PipelineRnpvAdapter": (
        "edgarito.services.valuation.intrinsic",
        "PipelineRnpvAdapter",
    ),
    "PropertyNavAdapter": (
        "edgarito.services.valuation.intrinsic",
        "PropertyNavAdapter",
    ),
    "ReitAffoAdapter": ("edgarito.services.valuation.intrinsic", "ReitAffoAdapter"),
    "ResidualIncomeService": (
        "edgarito.services.valuation.intrinsic",
        "ResidualIncomeService",
    ),
    "ResourceNavAdapter": (
        "edgarito.services.valuation.intrinsic",
        "ResourceNavAdapter",
    ),
    "SotpValuationService": (
        "edgarito.services.valuation.intrinsic",
        "SotpValuationService",
    ),
    "ValuationExecutor": ("edgarito.services.valuation.execution", "ValuationExecutor"),
    "ValuationInputCatalog": (
        "edgarito.services.valuation.execution",
        "ValuationInputCatalog",
    ),
    "wrap_fcff_result": ("edgarito.services.valuation.execution", "wrap_fcff_result"),
    "ProviderNeutralForwardMultiplesService": (
        "edgarito.services.valuation.relative",
        "ProviderNeutralForwardMultiplesService",
    ),
    "ProviderNeutralRelativeValuationService": (
        "edgarito.services.valuation.relative",
        "ProviderNeutralRelativeValuationService",
    ),
}


def __getattr__(name: str):
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attribute = target
    value = getattr(import_module(module_name), attribute)
    globals()[name] = value
    return value
