"""Provider-neutral deterministic forecast and valuation sanity validation."""

from .config import ForecastValidationConfig, ValidationConfig
from .contracts import (
    HUNDRED,
    ONE,
    ZERO,
    Category,
    Finding,
    ForecastRow,
    ForecastValidationArtifact,
    ForecastValidationCategory,
    ForecastValidationContext,
    ForecastValidationFinding,
    ForecastValidationResult,
    ForecastValidationSeverity,
    ForecastYearRow,
    Severity,
    TerminalMetrics,
    ValidationCategory,
    ValidationFinding,
    ValidationResult,
    ValidationSeverity,
    decimal_value,
)
from .registry import DEFAULT_RULE_REGISTRY, RuleRegistry, ValidationRule
from .service import ForecastSanityCheckService, ForecastValidationService

__all__ = [
    "Category",
    "DEFAULT_RULE_REGISTRY",
    "Finding",
    "ForecastRow",
    "ForecastSanityCheckService",
    "ForecastValidationArtifact",
    "ForecastValidationCategory",
    "ForecastValidationConfig",
    "ForecastValidationContext",
    "ForecastValidationFinding",
    "ForecastValidationResult",
    "ForecastValidationSeverity",
    "ForecastValidationService",
    "ForecastYearRow",
    "HUNDRED",
    "ONE",
    "RuleRegistry",
    "Severity",
    "TerminalMetrics",
    "ValidationCategory",
    "ValidationConfig",
    "ValidationFinding",
    "ValidationResult",
    "ValidationRule",
    "ValidationSeverity",
    "ZERO",
    "decimal_value",
]
